//go:generate mockgen -source=service.go -destination=../mocks/service_mock.go -package=mocks
package service

import (
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Cart represents shopping cart.
// It holds zero or more CartItems.
type Cart struct {
	ID    primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	Items []CartItem         `json:"items" bson:"items"`
}

// CartItem represents anytype of goods from shop.
type CartItem struct {
	ID          primitive.ObjectID `json:"id" bson:"id"`
	CartID      primitive.ObjectID `json:"cart_id" bson:"cart_id"`
	ProductName string             `json:"product" bson:"product"`
	Quantity    float64            `json:"quantity" bson:"quantity"`
}

// Service describes all functions for working with database.
type Service interface {
	// AddCart inserts cart to collection with primitiveObjectID generated by mongo.
	AddCart(ctx context.Context) (*Cart, error)
	// Cart returns cart with a specified id.
	Cart(ctx context.Context, id string) (*Cart, error)
	// AddItemToCart adds item to item list of a cart with a specified ID.
	AddItemToCart(ctx context.Context, cartID, productName string, quantity float64) (*CartItem, error)
	// RemoveItemFromCart removes an item with a specified ID from a cart with a specified ID.
	RemoveItemFromCart(ctx context.Context, cartID, cartItemID string) error
}
